name: Daily AI News - French
# Récupérer les articles de la journée

on:
  schedule:
    # Exécuter tous les jours à 10h00 UTC (12h00 heure française)
    - cron: '0 10 * * *'
  workflow_dispatch: # Permet de déclencher manuellement

jobs:
  send-french-newsletter:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      max-parallel: 1
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install openai requests python-dotenv
        
    - name: Run French newsletter script
      env:
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        RECIPIENTS: ${{ secrets.RECIPIENTS }}
      run: |
        python articles_batch_fr_server.py

  # Job de retry en cas d'échec du premier job
  retry-french-newsletter:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    needs: send-french-newsletter
    if: failure()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install openai requests python-dotenv
        
    - name: Run French newsletter script (retry)
      env:
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        RECIPIENTS: ${{ secrets.RECIPIENTS }}
      run: |
        echo "Retry attempt for French newsletter"
        python articles_batch_fr_server.py 