name: Daily AI News - English
# Récupérer les articles de la journée

on:
  schedule:
    # Exécuter tous les jours à 9h00 UTC (11h00 heure française)
    - cron: '0 9 * * *'
  workflow_dispatch: # Permet de déclencher manuellement

jobs:
  send-english-newsletter:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      max-parallel: 1
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install openai requests python-dotenv
        
    - name: Run English newsletter script
      env:
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        RECIPIENTS: ${{ secrets.RECIPIENTS }}
      run: |
        python articles_batch_en_server.py

  # Job de retry en cas d'échec du premier job
  retry-english-newsletter:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    needs: send-english-newsletter
    if: failure()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install openai requests python-dotenv
        
    - name: Run English newsletter script (retry)
      env:
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        RECIPIENTS: ${{ secrets.RECIPIENTS }}
      run: |
        echo "Retry attempt for English newsletter"
        python articles_batch_en_server.py 